version: '2'
services:
  openpnp:
    build: ./openpnp
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
    volumes:
       - /dev/ttyUSB0:/dev/ttyUSB0
       - /dev/ttyUSB1:/dev/ttyUSB1
       - /dev/ttyUSB2:/dev/ttyUSB2
#    devices:
#       - /dev/ttyUSB0:/dev/ttyUSB0
#       - /dev/ttyUSB1:/dev/ttyUSB1
#       - /dev/ttyUSB2:/dev/ttyUSB2
