version: '2.1'
services:
  openpnp:
    build: ./openpnp
    privileged: true
    restart: always
    network_mode: "host"
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.firmware: '1'
      io.balena.features.dbus: '1'
    devices:
       - /dev/ttyUSB0:/dev/ttyUSB0
       - /dev/ttyUSB1:/dev/ttyUSB1
       - /dev/ttyUSB2:/dev/ttyUSB2
       - /dev/bus/usb:/dev/bus/usb
       - /dev/dri
    expose:
       - 5900
       - 9090
    group_add:
      - video
    environment:
      WEB_PORT: 80
      DISABLE_PASSWORDS: false
  neko:
    image: "ghcr.io/m1k1o/neko/arm-xfce:latest"
    restart: unless-stopped
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
